name: C/C++ CI

on:
  push:
    branches: [ "szc_development" ]
  pull_request:
    branches: [ "szc_development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: sh ./build.sh

